all: vagrant-note.html vagrant-base.html

vagrant-note.html: vagrant-note.md
	maruku --html --output vagrant-note.html vagrant-note.md

vagrant-base.html: vagrant-base.md
	maruku --html --output vagrant-base.html vagrant-base.md
